// v2-data.jsx — RUDEL v2 (MVP Edition)
// 28 Karten: 10 Match (Paar) · 10 Squad (3–4) · 8 Rudel (alle).
// resolve: 'success' | 'vote_in_group' | 'pick_from_all'
//   success         → alle Teilnehmer:innen bekommen +2
//   vote_in_group   → eine Person aus der Gruppe gewinnt Abstimmung (+3)
//   pick_from_all   → Spielleitung tippt eine/mehrere aus dem ganzen Rudel an (+2 je)
// prompts (optional): wird beim Ziehen zufällig gewählt, ersetzt/ergänzt text.

const V2_THEME = {
  name: 'RUDEL',
  edition: 'MVP EDITION',
  festival: 'ROCK AM RING',
  year: '2026',
  dates: '03–07 JUNI',
  place: 'NÜRBURGRING',
};

const V2_POINTS = { success: 2, vote: 3, pick: 2 };

const V2_CARDS = [
  // ─── MATCH & MISSION · 2 Personen ───
  { id: 1,  type: 'match', participants: 'pair', title: 'GEHEIM-HANDSHAKE',
    text: 'Erfindet zusammen einen geheimen Handshake mit mindestens 4 verschiedenen Bewegungen. Macht ihn der Gruppe danach synchron vor.', timer: 60, resolve: 'success',
    twist: 'Mit verbundenen Augen – beide Augen zu.',
    drinkRule: "Patzer in der Vorführung: beide trinken einen Schluck." },
  { id: 2,  type: 'match', participants: 'pair', title: '5 GEMEINSAMKEITEN',
    text: 'Findet in 60 Sekunden 5 Dinge, die ihr beide gemeinsam habt. Aber: nichts Offensichtliches wie „wir sind beide hier" oder „beide haben Haare" – die zählen nicht.', timer: 60, resolve: 'success',
    twist: 'Ohne reden – nur Gesten, Mimik, oder aufs Handy malen.',
    drinkRule: "Schafft ihr keine 5? Beide trinken." },
  { id: 3,  type: 'match', participants: 'pair', title: 'FREMDE FRAGEN', category: '🫂 KENNENLERNEN',
    text: 'Stellt euch gegenseitig je 3 ungewöhnliche Fragen, die ihr normalerweise niemandem stellen würdet. Beide antworten ehrlich. Keine Wertung, einfach reden.', timer: 90, resolve: 'discuss' },
  { id: 4,  type: 'match', participants: 'pair', title: 'LIP-SYNC BATTLE',
    text: 'Sobald der nächste Song aus der Box läuft, performt ihr beide synchron Lip-Sync dazu. Mimik, Tanz, volle Festival-Show vor der Gruppe.', timer: 90, resolve: 'success',
    twist: 'Komplett in Zeitlupe – Slow-Motion.',
    drinkRule: "Wer aussteigt oder kichert, trinkt einen Schluck." },
  { id: 5,  type: 'match', participants: 'pair', title: 'LACHEN VERBOTEN',
    text: 'Eine Person setzt sich in den Campingstuhl. Die andere hat 60 Sekunden Zeit, sie zum Lachen zu bringen – ohne sie anzufassen. Grimassen, Witze, Tanz – alles erlaubt.', timer: 60, resolve: 'success',
    twist: "Beide Augen geschlossen – nur Stimme, Geräusche und Worte zählen.",
    drinkRule: "Wer als Erstes lacht oder anfasst, trinkt." },
  { id: 6,  type: 'match', participants: 'pair', title: 'PEINLICHKEITS-DUELL',
    text: 'Zeigt euch gegenseitig eure peinlichste Auto-Korrektur, Google-Suche oder Sprachnachricht aus dem Handy. Das Rudel stimmt am Ende ab, welche peinlicher war.', timer: 90, resolve: 'vote_in_group',
    twist: "Erzählt jeweils die Story der ANDEREN Person – ausgedacht.",
    drinkRule: "Die abgewählte Person trinkt einen Schluck." },
  { id: 7,  type: 'match', participants: 'pair', title: 'SIGNATURE-DRINK',
    text: 'Mixt zusammen aus allem, was am Camp da ist, einen neuen Signature-Drink. Gebt ihm einen Namen. Das Rudel probiert reihum und bewertet.', timer: 120, resolve: 'success',
    twist: "Eine Person mixt blind, die andere wählt die Zutaten.",
    drinkRule: "Wer den Drink nicht runterkriegt: noch ein Schluck extra." },
  { id: 8,  type: 'match', participants: 'pair', title: 'KLAMOTTEN-TAUSCH', category: '🎲 CHAOS',
    text: 'Tauscht JETZT ein Kleidungsstück miteinander – Pulli, Cap, Sonnenbrille oder Schuh. Wird bis zur nächsten Runde getragen, dann zurück.', timer: null, resolve: 'discuss' },
  { id: 9,  type: 'match', participants: 'pair', title: 'FAKE-BIOGRAFIE',
    text: 'Eine Person erzählt 60 Sekunden lang die komplett ausgedachte Lebensgeschichte der anderen Person – Heimatdorf, Beruf, Geschwister, Skandale. Je absurder, desto besser.', timer: 60, resolve: 'success',
    twist: "Erzählt die Story abwechselnd – Satz für Satz.",
    drinkRule: "Wer stockt oder lacht, trinkt." },
  { id: 10, type: 'match', participants: 'pair', title: 'BLIND BUILDER',
    text: 'Eine Person sucht ein zufälliges Foto auf dem Handy und beschreibt es nur mit Worten. Die andere baut das Bild aus Bechern, Stöcken und Krempel nach, ohne es zu sehen.', timer: 90, resolve: 'success',
    twist: 'Beide blind – beide Augen zu.',
    drinkRule: "Wenn das Endergebnis komplett daneben ist: beide trinken." },

  // ─── SQUAD MISSIONS · 3–4 Personen ───
  { id: 11, type: 'squad', participants: 'squad', title: 'KULT GRÜNDEN',
    text: 'Sucht euch einen zufälligen Gegenstand am Camp aus (Becher, Sonnenbrille, Stock). Gründet einen Kult darum: Name, Glaubenssatz, geheimes Ritual. Stellt euch dem Rudel vor.', timer: 120, resolve: 'success',
    twist: "Alle reden nur in einer ausgedachten Fantasy-Sprache.",
    drinkRule: "Wer beim Pitch kichert, trinkt." },
  { id: 12, type: 'squad', participants: 'squad', title: 'CAMP-WERBUNG',
    text: 'Erfindet einen 30-Sekunden-Werbespot für euer Camp – wie im TV. Slogan, Soundtrack-Imitation, übertriebene Klischees. Eine Person filmt mit dem Handy, der Rest schauspielt.', timer: 120, resolve: 'success',
    twist: "Komplett ohne Worte – nur Gesten, Mimik, Geräusche.",
    drinkRule: "Wer in der Werbung patzt, trinkt." },
  { id: 13, type: 'squad', participants: 'squad', title: 'FESTIVAL-THRON',
    text: 'Baut in 3 Minuten aus Campingstühlen, Bechern und allem, was rumliegt, den hässlichsten Festival-Thron. Eine Person aus eurem Squad setzt sich am Ende drauf und wird gekrönt.', timer: 180, resolve: 'success',
    twist: "Alle bauen mit verbundenen Augen.",
    drinkRule: "Wer am Ende nicht aktiv beigetragen hat, trinkt." },
  { id: 14, type: 'squad', participants: 'squad', title: 'CAMP-HYMNE',
    text: 'Erfindet zusammen eine Hymne für euer Camp – Melodie, Text, mindestens eine Strophe. Am Ende singt ihr sie laut und stolz vor dem ganzen Rudel.', timer: 120, resolve: 'success',
    twist: "Die Hymne wird operngerecht gesungen – voller Schmelz.",
    drinkRule: "Wer beim Singen aussetzt, trinkt." },
  { id: 15, type: 'squad', participants: 'squad', title: 'MENSCHLICHES KUNSTWERK',
    text: 'Stellt gemeinsam ein berühmtes Bild, Album-Cover oder Internet-Meme nach (Abbey Road, das ablenkte-Freund-Meme, …). Eine Person macht das Foto, das Rudel rät, was es ist.', timer: 90, resolve: 'success',
    twist: "Alle haben die Augen zu, Spielleitung dirigiert per Stimme.",
    drinkRule: "Wer am Foto fehlt oder zu spät kommt, trinkt." },
  { id: 16, type: 'squad', participants: 'squad', title: 'IMPRO-THEATER',
    text: 'Spielt eine kleine Theaterszene basierend auf dem Hinweis unten. Alle dürfen reden, sich bewegen und übertreiben. Macht eine echte Mini-Vorstellung daraus.', timer: 120, resolve: 'success',
    prompts: [
      'ORT: Festivalklo · BERUF: Influencer · PROBLEM: kein Klopapier mehr',
      'ORT: Wodka-Zelt · BERUF: Pfarrer · PROBLEM: die Eltern stehen davor',
      'ORT: Mosh Pit · BERUF: Yoga-Coach · PROBLEM: die Yoga-Matte ist weg',
      'ORT: Camping-Küche · BERUF: Sterne-Koch · PROBLEM: nur Ravioli & Bier',
      'ORT: Backstage · BERUF: Roadie · PROBLEM: Sänger fehlt, Show in 5 Min',
    ],
    twist: "Eine Person singt alles, statt zu sprechen.",
    drinkRule: "Wer aus der Rolle fällt, trinkt einen Schluck."},
  { id: 17, type: 'squad', participants: 'squad', title: 'CAMP-PARTEI',
    text: 'Gründet eine kleine Partei für euer Camp: Parteiname, Logo (gemalt oder gebaut), 3 Programmpunkte. Stellt euch dem Rudel mit einer kurzen Wahlrede vor.', timer: 120, resolve: 'success',
    twist: "Die komplette Wahlrede muss in Reimen sein.",
    drinkRule: "Wer bei der Wahlrede zögert, trinkt." },
  { id: 18, type: 'squad', participants: 'squad', title: 'VERKAUFSGENIES',
    text: 'Sucht euch einen völlig nutzlosen Gegenstand am Camp (kaputter Stock, leerer Becher, Steinchen) und verkauft ihn dem Rudel in einem überzeugenden Pitch wie auf einer Verkaufsshow.', timer: 90, resolve: 'success',
    twist: "Komplett in ausgedachter Fantasy-Sprache verkaufen.",
    drinkRule: "Wenn niemand kauft: jede:r aus dem Squad trinkt einen Schluck." },
  { id: 19, type: 'squad', participants: 'squad', title: 'FESTIVAL-BOYBAND',
    text: 'Werdet zur Festival-Boyband: Bandname, Signature-Tanzmove, Albumtitel. Performt am Ende einen 20-Sekunden-Auftritt vor dem Rudel.', timer: 120, resolve: 'success',
    twist: "Der Bandname muss den Lieblings-Snack aus eurem Squad enthalten.",
    drinkRule: "Wer im Auftritt patzt, trinkt." },
  { id: 20, type: 'squad', participants: 'squad', title: 'NOTAUFNAHME',
    text: 'Eine Person aus eurem Squad spielt überzeugend Patient:in mit unklaren Symptomen. Die anderen sind das Ärzteteam und stellen eine komplett absurde Diagnose plus Behandlungsplan. Performt das vor dem Rudel.', timer: 90, resolve: 'success',
    twist: "Die Diagnose komplett in Reimen.",
    drinkRule: "Wer aus der Rolle fällt, trinkt." },

  // ─── RUDEL CHALLENGES · alle spielen ───
  { id: 21, type: 'rudel', participants: 'all', title: 'WER WÜRDE EHER?',
    text: 'Die Spielleitung liest die Frage unten vor. Auf 3 zeigen alle gleichzeitig auf die Person aus dem Rudel, auf die das am ehesten zutrifft. Wer am häufigsten gezeigt wird, bekommt Punkte.', timer: 25, resolve: 'pick_from_all',
    prompts: [
      'Wer würde am ehesten einen Tag im Backstage verschwinden?',
      'Wer würde am ehesten den falschen Bus nach Hause nehmen?',
      'Wer würde am ehesten morgen früh noch tanzen?',
      'Wer würde am ehesten dem Sänger anschreiben?',
      'Wer würde am ehesten ein Tattoo am Festival kriegen?',
      'Wer würde am ehesten die Klospülung zerstören?',
    ],
    twist: "Alle zeigen mit den FÜSSEN, nicht mit den Händen.",
    drinkRule: "Die am häufigsten gezeigte Person trinkt einen Schluck."},
  { id: 22, type: 'rudel', participants: 'all', title: 'SORTIERT EUCH',
    text: 'Stellt euch in eine Reihe sortiert nach dem Kriterium unten. Aber: ihr dürft KEIN Wort sagen. Nur Gesten, Mimik, Zeichen. Am Ende wird gemeinsam überprüft.', timer: 60, resolve: 'success',
    prompts: [
      'Nach Alter (jung → alt)',
      'Nach Körpergröße (klein → groß)',
      'Nach Anzahl bereister Länder',
      'Nach „wie betrunken war ich gestern" (1–10)',
      'Nach Stunden Schlaf letzte Nacht',
      'Nach Anzahl Festivals besucht',
    ],
    twist: "Sortiert euch mit verbundenen Augen.",
    drinkRule: "Wer auch nur ein einziges Wort sagt, trinkt."},
  { id: 23, type: 'rudel', participants: 'all', title: 'MENSCHEN-BINGO',
    text: 'Schaut die Aussage unten an. Geht durchs Rudel und findet jemanden, auf den sie zutrifft. Wenn jemand passendes findet, wird laut gerufen. So lange suchen, bis alle Aussagen ein Match haben.', timer: 180, resolve: 'success',
    prompts: [
      'War schon auf mehr als 5 Festivals',
      'Hat ein Tattoo, das niemand kennt',
      'Hat sich schon mal einen Knochen gebrochen',
      'War schon mal auf der Bühne',
      'Spricht eine 3. Sprache',
      'Hat heute weniger als 4h geschlafen',
    ],
    twist: "Nur mit Gesten fragen – kein Reden erlaubt.",
    drinkRule: "Die letzte Person ohne Match-Treffer trinkt."},
  { id: 24, type: 'rudel', participants: 'all', title: 'GEHEIM-ABSTIMMUNG',
    text: 'Lest die Frage unten. Jede:r läuft kurz zur Spielleitung und flüstert ihr/ihm eine Person aus dem Rudel ins Ohr. Die Person mit den meisten Stimmen gewinnt Punkte.', timer: 60, resolve: 'pick_from_all',
    prompts: [
      'Wer hat vermutlich die verrückteste Story?',
      'Wer hat das beste Lachen?',
      'Wer ist heimlich der/die coolste hier?',
      'Wer würde am besten als Festival-Maskottchen passen?',
      'Wer hat den geilsten Style?',
    ],
    twist: "Wahl per Pantomime statt Flüstern.",
    drinkRule: "Die Person mit den meisten Stimmen trinkt einen Schluck."},
  { id: 25, type: 'rudel', participants: 'all', title: 'WAHR ODER GELOGEN',
    text: 'Eine Person aus dem Rudel erzählt eine Geschichte aus dem eigenen Leben. Sie kann komplett wahr oder komplett erfunden sein. Am Ende stimmt der Rest ab: wahr oder gelogen? Auflösung folgt.', timer: 90, resolve: 'success',
    twist: "Erzähler trägt Sonnenbrille – Mimik komplett versteckt.",
    drinkRule: "Wer falsch rät, trinkt. Bei wahrer Story trinkt der Erzähler doppelt." },
  { id: 26, type: 'rudel', participants: 'all', title: 'HOT TAKES', category: '💬 HOT TAKE',
    text: 'Lest die These unten. Stellt euch auf eine Seite: rechts = volle Zustimmung, links = totaler Bullshit. Kurz diskutieren, dann nächste Karte.', timer: 60, resolve: 'discuss',
    prompts: [
      '„Ananas gehört auf Pizza.“',
      '„Wer nüchtern aufs Festival fährt, macht etwas falsch.“',
      '„Ein Dixi-Klo um 4 Uhr morgens ist ein Abenteuer.“',
      '„15€ für einen Döner sind völlig okay."',
      '„Headliner ist überbewertet – die kleinen Bühnen sind besser."',
      '„Pfand-Becher gehört abgeschafft."',
      '„Duschen am Festival ist Zeitverschwendung."',
      '„Camping ohne Pavillon ist kein echtes Camping."',
      '„Sonnenbrille auch nachts ist ein Move."',
    ],
    drinkRule: "Wer als Letzte:r Position bezieht oder keine Meinung hat: einen Schluck."},
  { id: 27, type: 'rudel', participants: 'all', title: 'DAS RUDEL ENTSCHEIDET',
    text: 'Zwei Freiwillige aus dem Rudel vertreten je eine Seite der Frage unten und debattieren 60 Sekunden lang. Am Ende klatscht das Rudel für die überzeugendere Seite – die Spielleitung tippt die Person an.', timer: 90, resolve: 'pick_from_all',
    prompts: [
      'Pizza Hawaii: Verbrechen oder Genie?',
      'Festival oder Strandurlaub – was ist besser?',
      'Nachts schlafen oder durchmachen?',
      'Techno oder Rock – was ist die einzig wahre Musik?',
    ],
    twist: "Beide Seiten singen ihre Argumente statt zu reden.",
    drinkRule: "Die verlierende Seite trinkt einen Schluck."},
  { id: 28, type: 'rudel', participants: 'all', title: 'RUDEL-RANKING', category: '🎲 CHAOS',
    text: 'Sortiert euch in eine Reihenfolge basierend auf der Frage unten. Schreibt es auf einem Zettel auf. Morgen früh wird verglichen, wer richtig getippt hat. Heute keine Punkte.', timer: 60, resolve: 'discuss',
    prompts: [
      'Wer schläft heute zuerst ein?',
      'Wer ist morgen zuerst wach?',
      'Wer trinkt heute am meisten Wasser?',
      'Wer verliert zuerst sein Handy?',
      'Wer hat heute den krassesten Hangover?',
    ]},

  // ─── ERWEITERUNG · zusätzliche coole Karten ───
  { id: 29, type: 'match', participants: 'pair', title: 'SUPERHELDEN-DUO',
    text: 'Erfindet zusammen ein Superhelden-Duo: je einen Heldennamen, eine gemeinsame Superkraft, eine peinliche Schwäche. Macht eine 30-Sekunden-Vorstellung vor dem Rudel.', timer: 75, resolve: 'success',
    twist: 'Alles muss sich reimen.',
    drinkRule: "Wer bei der Vorstellung lacht, trinkt." },
  { id: 30, type: 'match', participants: 'pair', title: 'BLIND-PORTRAIT',
    text: 'Eine Person aus dem Paar zeichnet mit geschlossenen Augen das Gesicht der anderen auf ein Stück Pappe oder einen Becher. Das Rudel rät am Ende, wen die Zeichnung darstellen soll.', timer: 60, resolve: 'success',
    twist: "Beide malen gleichzeitig blind – Doppel-Portrait.",
    drinkRule: "Wenn das Rudel die Person nicht erkennt: beide trinken." },
  { id: 31, type: 'match', participants: 'pair', title: 'BANDNAMEN-FABRIK',
    text: 'Erfindet in 60 Sekunden zusammen 5 möglichst absurde Bandnamen plus jeweils ein Musikgenre. Lest sie laut dem Rudel vor – das Rudel klatscht beim besten Namen.', timer: 60, resolve: 'success',
    twist: 'Alle 5 Namen müssen mit demselben Buchstaben starten.',
    drinkRule: "Wer keinen Bandnamen beisteuert, trinkt." },
  { id: 32, type: 'match', participants: 'pair', title: 'SONG-EMOJIS',
    text: 'Eine Person tippt einen bekannten Songtitel NUR mit Emojis ins Handy und hält es der anderen Person hoch. Die andere muss den Song erraten. Reden ist verboten.', timer: 60, resolve: 'success',
    twist: "Statt Emojis nur ASCII-Smileys.",
    drinkRule: "Wer den Song nicht errät, trinkt." },
  { id: 33, type: 'match', participants: 'pair', title: 'DREI KLEINE DINGE', category: '🫂 KENNENLERNEN',
    text: 'Erzählt euch je 3 kleine Dinge, die euch heute gut gelaunt gemacht haben. Kann winzig sein – sonniges Wetter, ein guter Snack, ein bestimmter Song. Keine Wertung, einfach reden.', timer: 60, resolve: 'discuss' },

  { id: 34, type: 'squad', participants: 'squad', title: 'TURM-BAU',
    text: 'Baut zusammen in 2 Minuten den höchsten freistehenden Turm aus Bechern, Dosen, Stöcken und allem, was am Camp rumliegt. Muss am Ende mindestens 10 Sekunden stehen ohne umzufallen.', timer: 120, resolve: 'success',
    twist: "Nur eine Hand pro Person erlaubt.",
    drinkRule: "Turm kippt um: jede:r aus dem Squad trinkt einen Schluck." },
  { id: 35, type: 'squad', participants: 'squad', title: 'GEHEIM-ZEICHEN',
    text: 'Erfindet zusammen ein 3-teiliges Geheim-Zeichen mit Händen oder Körper. Übt es kurz ein. Über den Abend müsst ihr es noch 3× spontan gemeinsam ausführen, wenn die Spielleitung „SQUAD!" ruft.', timer: 90, resolve: 'success',
    twist: "Das Geheimzeichen muss ein Geräusch enthalten.",
    drinkRule: "Wer das Zeichen heute Abend vergisst, trinkt 2 Schlucke." },
  { id: 36, type: 'squad', participants: 'squad', title: 'TANZ-TUTORIAL',
    text: 'Erfindet zusammen einen 4-Schritte-Tanzmove. Bringt ihn dem Rudel bei – Schritt für Schritt. Am Ende führen ALLE den Move synchron einmal aus.', timer: 120, resolve: 'success',
    twist: 'Alle Moves rückwärts.',
    drinkRule: "Wer im Rudel den Move nicht mittanzt, trinkt." },

  { id: 37, type: 'rudel', participants: 'all', title: 'PANTOMIME-KETTE',
    text: 'Stellt euch in einer Reihe auf. Die erste Person sieht einen Begriff auf dem Handy und spielt ihn der zweiten Person stumm vor. Diese spielt es der dritten vor und so weiter. Die letzte rät den Begriff laut.', timer: 120, resolve: 'success',
    twist: 'Ohne Hände – nur Körper, Füße, Mimik.',
    drinkRule: "Falscher Begriff am Ende: alle in der Kette trinken einen Schluck." },
  { id: 38, type: 'rudel', participants: 'all', title: 'WORT-KETTE',
    text: 'Erzählt zusammen eine Geschichte – aber jede:r sagt nur EIN Wort, dann ist die nächste Person dran. Reihum im Kreis. Wer stockt, lacht oder den Satz nicht weiterführt, scheidet diese Runde aus.', timer: 90, resolve: 'success',
    drinkRule: 'Wer abbricht oder stockt: trinkt einen Schluck.',
    twist: "Jedes Wort muss mit dem letzten Buchstaben des vorherigen Wortes anfangen." },
  { id: 39, type: 'rudel', participants: 'all', title: 'DREI ECKEN', category: '💬 HOT TAKE',
    text: 'Macht 3 Ecken am Camp: links = JA, rechts = NEIN, Mitte = VIELLEICHT. Die Spielleitung liest die Frage unten vor. Jede:r stellt sich in eine Ecke. Kurz diskutieren, dann nächste Karte.', timer: 45, resolve: 'discuss',
    prompts: [
      'Würdest du nochmal auf dasselbe Festival, wenn du wüsstest, dass es regnet?',
      'Soll die Spielleitung morgen früh laut Musik aufdrehen, um alle zu wecken?',
      'Ist „nur ein Bier" eine Lüge?',
      'Soll Pfand verdoppelt werden?',
      'Würdest du dein Handy für ein Wochenende komplett abgeben?',
      'Schlafsack oder Decke – was ist Camping-richtig?',
      'Sollten Camping-Stühle einen Festival-Pass-Bonus geben?',
    ],
    drinkRule: "Wer in der Minderheits-Ecke steht, trinkt einen Schluck."},

  // ─── BEWEGUNG · raus aus dem Stuhl ───
  { id: 40, type: 'match', participants: 'pair', title: 'RÜCKEN-AN-RÜCKEN',
    text: 'Setzt euch Rücken an Rücken auf den Boden und hakt eure Arme ineinander. Versucht zusammen aufzustehen, ohne die Hände auf den Boden zu stützen. Klingt easy – ist es nicht.', timer: 60, resolve: 'success',
    twist: "Beide haben die Augen zu.",
    drinkRule: "Wenn ihr es nicht schafft: beide trinken." },
  { id: 41, type: 'match', participants: 'pair', title: 'STATUEN-SPIEGEL',
    text: 'Eine Person bewegt sich in Zeitlupe, die andere spiegelt jede Bewegung exakt. Macht es 60 Sekunden lang. Am Ende rät das Rudel, wer geführt und wer gespiegelt hat.', timer: 60, resolve: 'success',
    twist: 'Rollen wechseln alle 10 Sekunden – ohne Pause.',
    drinkRule: "Wer als Erste:r aus dem Spiegel ausbricht, trinkt." },

  { id: 42, type: 'squad', participants: 'squad', title: 'LUFT-VOLLEYBALL',
    text: 'Nehmt einen leichten Gegenstand: einen aufgeblasenen Plastikbeutel oder einen leeren Becher. Haltet ihn 60 Sekunden lang in der Luft – aber nur mit Kopf, Ellbogen und Knien. Hände verboten.', timer: 60, resolve: 'success',
    twist: "Nur Schultern und Knie – Kopf verboten.",
    drinkRule: "Beutel fällt runter: alle Squad-Leute trinken einen Schluck." },
  { id: 43, type: 'squad', participants: 'squad', title: 'STAFFEL-WASSER',
    text: 'Füllt einen Becher randvoll mit Wasser. Tragt ihn nacheinander einmal um euer Camp – aber rennend. Übergabe von Hand zu Hand. Am Ende muss noch möglichst viel Wasser drin sein.', timer: 90, resolve: 'success',
    twist: "Der Becher wird nur mit dem Mund weitergegeben.",
    drinkRule: "Wer Wasser verschüttet, trinkt einen Schluck." },
  { id: 44, type: 'squad', participants: 'squad', title: 'CHOREO-10',
    text: 'Erfindet zusammen einen 10-Sekunden-Tanzmove. Alle aus eurem Squad machen am Ende exakt dasselbe – komplett synchron. Performt das einmal vor dem Rudel.', timer: 90, resolve: 'success',
    twist: "Alle Moves müssen Klatschen enthalten.",
    drinkRule: "Wer aus dem Sync fällt, trinkt." },

  { id: 45, type: 'rudel', participants: 'all', title: 'LA OLA',
    text: 'Macht eine saubere La Ola im Kreis – sitzend oder stehend, der Reihe nach aufstehen und wieder hinsetzen. Muss flüssig und im Takt sein. 3 Versuche, dann zählt sie.', timer: 45, resolve: 'success',
    twist: 'Rückwärts durch den Kreis.',
    drinkRule: "Wer aus dem Takt rauskommt, trinkt." },
  { id: 46, type: 'rudel', participants: 'all', title: 'FREEZE-POSE',
    text: 'Die Spielleitung ruft „GO" – alle tanzen wild zu Musik. Auf „STOPP" friert JEDE Person sofort in einer Pose ein. Spielleitung schaut sich alle Posen an und tippt die lustigste an – die kriegt Punkte.', timer: 30, resolve: 'pick_from_all',
    twist: "Auf STOPP totale Stille – auch kein Lachen.",
    drinkRule: "Wer bei STOPP weiter zappelt, trinkt einen Schluck." },
  { id: 47, type: 'rudel', participants: 'all', title: 'TOTALE STILLE', category: '🎲 CHAOS',
    text: '30 Sekunden komplette Stille und Stillstand. Niemand redet, niemand bewegt sich, niemand lacht. Wer zuckt, lacht oder redet, scheidet aus. Am Ende einfach weiter – keine Punkte.', timer: 30, resolve: 'discuss',
    drinkRule: 'Wer zuckt, lacht oder redet: trinkt einen Schluck.' },

  // ─── DRINK-ONLY · nur im „mit Trinken"-Modus ───
  { id: 48, type: 'rudel', participants: 'all', title: 'BECHER-ROULETTE', drinksRequired: true,
    text: 'Füllt heimlich 4 Becher: 3 mit einem normalen Getränk, 1 mit einem Shot. 4 Personen aus dem Rudel trinken alle gleichzeitig mit Pokerface. Das restliche Rudel rät, wer den Shot hatte.', timer: 60, resolve: 'pick_from_all' },
  { id: 49, type: 'rudel', participants: 'all', title: 'PROST-SPRACHEN', drinksRequired: true,
    text: 'Setzt euch in einen Kreis. Reihum stößt jede:r mit jemandem an und sagt „Prost" in einer anderen Sprache (Cheers, Salud, Skål, Kanpai, …). Wer eine Sprache wiederholt oder stockt, trinkt einen Schluck.', timer: 60, resolve: 'success' },
  { id: 50, type: 'match', participants: 'pair', title: 'KING\'S CUP DUELL', drinksRequired: true,
    text: 'Eine Person aus dem Paar erfindet eine kleine Trinkregel (z. B. „wer ‚ich\' sagt, trinkt einen Schluck"). Die andere fügt eine zweite Regel hinzu. Beide Regeln gelten ab jetzt – bis zur nächsten Match-Karte.', timer: 45, resolve: 'success' },

  // ─── ECHTES TRINKSPIEL · weitere drink-only Karten ───
  { id: 51, type: 'squad', participants: 'squad', title: 'FLIP CUP', drinksRequired: true,
    text: 'Stellt 4 Becher mit etwas Getränk an die Tischkante. Reihum: austrinken, Becher umdrehen, mit dem Finger so „flippen", dass er auf dem Kopf stehen bleibt. Wer\'s nicht beim ersten Versuch schafft, trinkt nochmal und versucht weiter.', timer: 120, resolve: 'success' },
  { id: 52, type: 'rudel', participants: 'all', title: 'ICH HAB NOCH NIE', drinksRequired: true, category: '🎲 CHAOS',
    text: 'Setzt euch in einen Kreis. Reihum sagt jede:r eine Aussage „Ich hab noch nie…". Wer\'s schon mal gemacht hat: trinkt einen Schluck. 5 Runden lang reihum.', timer: 180, resolve: 'discuss' },
  { id: 53, type: 'rudel', participants: 'all', title: 'BUZZ-ZÄHLEN', drinksRequired: true,
    text: 'Zählt reihum laut von 1 hoch. Bei jeder 7 und jedem Vielfachen von 7 (14, 21, 28…) sagt ihr stattdessen „BUZZ". Wer falsch zählt oder zögert, trinkt einen Schluck. Dann wieder bei 1 anfangen.', timer: 90, resolve: 'success' },
  { id: 54, type: 'rudel', participants: 'all', title: 'ABC-COCKTAIL', drinksRequired: true,
    text: 'Reihum nennt jede:r eine Cocktail- oder Drink-Zutat alphabetisch (A wie Apfelsaft, B wie Bier, C wie Cointreau…). Wer stockt, wiederholt oder unfair improvisiert, trinkt einen Schluck.', timer: 90, resolve: 'success' },
];

Object.assign(window, { V2_THEME, V2_POINTS, V2_CARDS });
